version: "3.8"

services:
  api:
    container_name: tasks-api
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    container_name: tasks-mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - tasks-mysql:/var/lib/mysql
    env_file:
      - db.env

volumes:
  tasks-mysql:
