version: "3.8"

services:
  api:
    container_name: tasks-api
    build: .
    command: sh -c "npx nodemon src/index.ts"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/home/app
    env_file:
      - .env
  mysql:
    container_name: tasks-mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - tasks-mysql:/var/lib/mysql
    env_file:
      - db.env

volumes:
  tasks-mysql:
